OpenBoardView/OpenBoardView

- src/BoardView.cpp
Restructured the window layout so that there's no overlapping between
the main menu bar, board drawing area, and status bar.
Check for hover instead of focus in BoardView::HandleInput(). This
also means that zooming will work when OpenBoardView is not the
focused application.
Fixes #30
> Fix an issue where we lose focus after menu items are used.

- README.md
- src/BoardView.cpp
- src/BoardView.h
Inspired by inflex's main menu, I've moved the Net, Component and About buttons into Search and Help menus. I've also added a Controls dialog to the Help menu and updated the controls listed in the README.
All dialogs and windows are now handles in the overlay and windows section.
> Reorganise main menu and add Controls dialog

- src/openboardview/BRDBoard.cpp
Some BRD files have part type set as 1/2 to represent top/bottom respectively.  This merge brings the fix in to master.
> Attempt to fix situation where parts appear on both sides

- src/openboardview/main_opengl.cpp
can be loaded in Windows by the double-click method (without this fix it won't work by default because OBV expects -i <file>
> Added single-parameter file load mode so that associated filenames/types

- CMakeLists.txt
If there is no .git directory for example from a release tarball, OBV_BUILD is
set to "R". This patch should determine if git tree is present and if not use
PROJECT_VERSION as OBV_BUILD.
Also allow to set custom OBV_BUILD from command line or configuration.
Issue #79
> CMake: OBV_BUILD as a build option and use PROJECT_VERSION if there is no git

- CMakeLists.txt
- build.sh
Common use case is to pass `DESTDIR` as a destination directory,
and `CMAKE_INSTALL_PREFIX` as a prefix:
```bash
cmake -DCMAKE_INSTALL_PREFIX=/usr
DESTDIR=/tmp/root  make install
```
Without this change, this would result in unwanted prefix. And
there was no way of controlling install directory externally.
> CMake: Don't overwrite CMAKE_INSTALL_PREFIX

- utilities/bvconv.sh
According to what is OBV looking for, this was not producing a
valid file.
- Spelling in header
- [Layout] to <<Layout>> etc.
- Tab as column separator
> bvconv: Fix it so that it produces readable files

- build.sh
This allows `build.sh` to completely build OBV on systems that don't have bash, and It'll still work on systems that do. I've tested this on NetBSD 7.1, OS X 10.12.6, and Debian 8.
> Remove the dependency on bash

- src/openboardview/BoardView.cpp
Not as if it's something what people usually do, but it's easy enough to click by accident.
> Fix crash when clicking on CLEAR before loading board

- .gitignore
- src/openboardview/BRDBoard.cpp
- src/openboardview/FileFormats/ASCFile.cpp
- src/openboardview/FileFormats/BDVFile.cpp
- src/openboardview/FileFormats/BRD2File.cpp
- src/openboardview/FileFormats/BRDFile.cpp
- src/openboardview/FileFormats/BRDFile.h
- src/openboardview/FileFormats/BVRFile.cpp
- src/openboardview/FileFormats/CSTFile.cpp
- src/openboardview/FileFormats/FZFile.cpp
- Renamed BRDPart::type to BRDPart::mounting_side
- Introduced enum for BRDPart::mounting_side
There is a bit hardly understood-able code around the BRDBoard::BRDBoard(const BRDFile *const boardFile), what I have not touched, but I can clean it up to if required.
> BRDPart::type refactoring

- src/openboardview/platform.h
- src/openboardview/unix.cpp
- src/openboardview/utils.cpp
- src/openboardview/utils.h
- src/openboardview/win32.cpp
When one tries to pass a directory instead of file name from
command line OpenBoardView will crash. This happens because
of ftell() returns -1 which is cast to unsigned value. There
will be a memory allocation error right after that.
> Fix crash when attempting to open directory from command line

- src/openboardview/CMakeLists.txt
Pretty sure Linux is the only one needing `libdl`, cf.
https://linux.die.net/man/3/dlopen
https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man3/dlopen.3.html
https://www.freebsd.org/cgi/man.cgi?query=dlopen&sektion=3
https://man.openbsd.org/dlopen.3
http://netbsd.gw.com/cgi-bin/man-cgi?dlopen+3+NetBSD-current
https://www.dragonflybsd.org/cgi/web-man?command=dlopen&section=3
https://docs.oracle.com/cd/E26502_01/html/E29034/dlopen-3c.html
https://docs.oracle.com/cd/E86824_01/html/E54772/libdl-3lib.html
> Only link against libdl on Linux

- src/openboardview/BoardView.cpp
Some commits with no-functional-changes related on silencing strict compiler warnings.
Those warnings are often helping catching real issues in the code, and those are something we keep enabled in Blender. Not sure what is usually policy to deal with such warnings, just used Google style for that. Again, something we use in Blender and some other related projects.
Did some cleanup to help keeping my terminal outputs clean while looking in some other bug.
> Warning cleanup

- src/openboardview/unix.cpp
If XDG_CONFIG_HOME and XDG_DATA_HOME are set, the current directory is used because they never get added to the path.
> Fix get_user_dir for Linux when XDG env var is set

- src/openboardview/FileFormats/ASCFile.cpp
- src/openboardview/FileFormats/ASCFile.h
- src/openboardview/FileFormats/BDVFile.cpp
- src/openboardview/FileFormats/BRD2File.cpp
- src/openboardview/FileFormats/BRDFile.cpp
- src/openboardview/FileFormats/BRDFile.h
- src/openboardview/FileFormats/BVRFile.cpp
- src/openboardview/FileFormats/FZFile.cpp
The issue was caused by stringfile() allocating memory for lines pointers, and
this memory was never freed (even though the comment of the function explicitly
mentioned that the result is to be freed).
This commit replaces allocation of bare memory with using std::vector to store
pointers to all lines. This saves us a trouble of manually freeing memory.
Most of the board parsers became shorter, but some of them are still using
bare pointers internally because they need to pass line pointer around and
modify it (i.e. skip lines). It is probably possible to make that code more
modern, but could happen as a separate change.
> Fix memory leak happening when opening file

- src/openboardview/BoardView.cpp
In situations where no board outline has been generated (either lack of data in the board file or parsing incompatibility),  good to have a failsafe outline generated.
> Board outline failsafe generator

- src/openboardview/BoardView.cpp
- src/openboardview/FileFormats/BRDFile.cpp
Need more files to check consistency of this variant. Some nets aren't referenced in the file so a lot of pads are left unconnected apparently.
> Some tweaks to support Lenovo brd format variant (ex. T420)

- src/openboardview/BoardView.cpp
This implements feature request #172
"Copy" small button is added to the first line of a component.
It copies multiline text, containing
reference designator (and description if present) on 1st line,
pin names and associated in a separate line for every pin
> Copy to clipboard for component and its pins.

- src/openboardview/BRDBoard.cpp
- src/openboardview/BoardView.cpp
The first commit improves ground rendering: it is rendered in distinguished color among
the set of pins highlited by belonging to the same component.
The second commit improves detection of ground pins - they weren't detected for some files
> Improve ground pins handling

- build.sh
- src/openboardview/CMakeLists.txt
These patches makes it run on Haiku.
- use more portable way to count CPU cores in build.sh
- really make GTK optional, we don't have it.
- cache some `tput` results, devices runtime by 3 in a Haiku VM. Even on Linux it devices by 5 user time.
> Misc patches for Haiku support

- CMakeLists.txt
Optimized released binaries provides noticable speedup while working with huge boards.
> Build in optimized release mode when no CMAKE_BUILD_TYPE type is specified

- src/openboardview/BRDBoard.cpp
- src/openboardview/BRDBoard.h
- src/openboardview/BoardView.cpp
- src/openboardview/BoardView.h
- src/openboardview/CMakeLists.txt
- src/openboardview/FileFormats/ADFile.h
- src/openboardview/FileFormats/ASCFile.cpp
- src/openboardview/FileFormats/ASCFile.h
- src/openboardview/FileFormats/BDVFile.cpp
- src/openboardview/FileFormats/BDVFile.h
- src/openboardview/FileFormats/BRD2File.cpp
- src/openboardview/FileFormats/BRD2File.h
- src/openboardview/FileFormats/BRDAllegroFile.h
- src/openboardview/FileFormats/BRDFile.cpp
- src/openboardview/FileFormats/BRDFile.h
- src/openboardview/FileFormats/BRDFileBase.cpp
- src/openboardview/FileFormats/BRDFileBase.h
- src/openboardview/FileFormats/BVR3File.h
- src/openboardview/FileFormats/BVRFile.cpp
- src/openboardview/FileFormats/BVRFile.h
- src/openboardview/FileFormats/CADFile.cpp
- src/openboardview/FileFormats/CADFile.h
- src/openboardview/FileFormats/CSTFile.h
- src/openboardview/FileFormats/FZFile.cpp
- src/openboardview/FileFormats/FZFile.h
Preparations before introducing gencad format:
* Separate specific BRDFile implementation from common base class BRDFileBase.
* Utilize BRDPartMountingSide for the nails side marking
* Factor out Nails-as-pins conversion to a method of BRDFileBase from specific BRD2 implementation.
> Introduce BRDFileBase and cleanup nail handling

- src/openboardview/BoardView.cpp
- src/openboardview/BoardView.h
On clicking checkboxes/radiobuttons:
- added immediate update of search preview by currently focused column
- removed resetting of focused search column to first.
(search column is kept while changing searching parameters by storing its index in m_active_search_column)
On changing search column:
- added immediate update of highlighted parts (search preview by currently focused column).
- so tabbing from first column with text to the second empty column immediately clears preview.
On clearing text inside search column:
- added clearing of search preview. Before this patch the preview showed the results just before the clearing.
On opening popup again after performing search with Enter:
- added immediate previewing of text kept from previous search
- the focused column is kept, not reset to …
> Improved interactive update of search-preview-highlighted parts.

- src/openboardview/FileFormats/GenCADFile.cpp
673a43d5c265e441e21ac684053b0a133e5a88dc makes pins marked as through-hole visible on both sides, but for unknown to me reason those pins cannot be selected with a mouse click on the other side of the board. Not sure if bug or doing something wrong. The same issue occurs with landrex `*.brd` files.
9d000d84c45955cb4f0e85cdb322e1d2e9f17699 is a workaround for this issue which additionally creates extra clutter on screen by duplicating component outline on both sides. (but THT pads can be selected on either side now). Would be for the best if this commit wasn't needed/merged and underlying issue was fixed.
This feature seems to be distinct enough and requires a lot of testing so I have put it as separate from #247 pull request
Lack of this feature is especially noticeable in …
> GenCAD THT pins support

- src/openboardview/Board.cpp
- src/openboardview/Board.h
- src/openboardview/BoardView.cpp
- src/openboardview/CMakeLists.txt
- src/openboardview/Searcher.cpp
- src/openboardview/Searcher.h
The new "Including Part Number" checkbox is added to search dialog.
It enables searching the "msgcode" string attached to each element.
For me it is useful for cases like answering
"Where did they put that P-mosfet in this revision of design?"
(datasheets I'm working with has a lot of msgcode data - part number, Ohm values, even packages).
It's checkbox disabled by default,
since it's UI is a bit less expected then other searches -
the results that are showing below search fields are still names,
not msgcodes, so it is not so immediately obvious
why they are included there.
Also, I'm a not 100% sure of portability
of pointer-to-member-of-template class that I used in Searcher.cpp,
but I do not know actual problems with it.
> Search dialog: add searching by details (part mfg code and pin names)

- src/openboardview/BRDBoard.cpp
- src/openboardview/BRDBoard.h
- src/openboardview/Board.h
- src/openboardview/BoardView.cpp
- src/openboardview/BoardView.h
- src/openboardview/FileFormats/BRDFileBase.h
- src/openboardview/FileFormats/GenCADFile.cpp
- src/openboardview/FileFormats/GenCADFile.h
Should mostly fix outline problems of GenCAD.
Hopefully I didn't break too many things
Breaks at least board fill but really who cares about that.
Also arcs beginning/end do not match exactly with the previous/next line, could be due to float/int conversions.
@swiftgeek @galkinvv
> Segmented outline drawing mode for GenCAD

- CMakeLists.txt
- src/CMakeLists.txt
- src/sqlite3/CMakeLists.txt
Support for CMake policies below 3.10 is deprecated since CMake 3.31 https://cmake.org/cmake/help/v4.0/command/cmake_minimum_required.html#policy-version
The oldest platform targeted by OpenBoardView is RHEL8-like distros, having CMake 3.11.
So switch to requitring CMake 3.11 - this automatically switches all older policies to NEW behaviour, so explicit policy seting is removed
Explicit declaration of needed version for subfolders is removed
Note: zlib submodule is not updated for CMake4 support,
so platforms having CMake4 are expected to provide system zlib.
> CMake: fix compatibility with CMake 4.x on mingw-w64-ucrt

- src/openboardview/CMakeLists.txt
Add missing PLIST Bundle parameter that is required for File->Open to work on Sequoia.
> Fix for non working FileOpen on macOS Sequoia

- README.md
fix fedora package dependencies as Fedora has changed how they do group installs. This was tested on Fedora Linux 41 Workstation Edition
> Update README.md, fix fedora package dependencies

- src/openboardview/FileFormats/GenCADFile.cpp
`sprintf` is incredibly slow, and during profiling with my specific use case this was the hottest function. By using `std::string` in this single function I was able to cut the load time in half.
Before:
After:
Ideally because this function is only called from *internal* callees' with only 6(?) or so variations we'd just have a switch with `constexpr char*`'s, but this is the most minimally invasive patch.
> GenCAD: Perf fix in get_nonquoted_or_quoted_string_child
